name: ai-tests
dependencies:
  - python==3.9.5
  - numpy==1.19.0
  - jupyterlab==3.0.16
  - matplotlib==3.4.2
  - pip==19.3.1
  - numba==0.45.1
  - scipy==1.3.1
  - scikit-learn==0.20.3
  - scikit-image==0.15.0
  - pandas==0.25.3
  - seaborn==0.11.0
  - astropy==4.0
  - h5py==2.10.0



